### ISSUE TITLE
Uploading Excel Schedule gives error

### ISSUE THREAD

**Issue by michaeljzucker** [SportsConcierge/scheduler#1]
Oops!
An unexpected error occurred
Sorry, an unexpected error occurred
[2016 HOHHC Master schl.revised.date.xlsx](https://github.com/SportsConcierge/scheduler/files/1117253/2016.HOHHC.Master.schl.revised.date.xlsx)

**Comment by rdwallis** [comment]
This is fixed.  The file format was different from the original file.  Closing.  Reopen if it's still broken for you

**Comment by Steve-IZP** [comment]
Still having issues.  Will the upload only work if all fields are recognized and the format is the same?

**Comment by rdwallis** [comment]
Yes the format has to be exactly the same.  It can only read files that are formatted the same as the original Heartland Holiday Classic file.

**Comment by Steve-IZP** [comment]
So then I think we need to decide on a standard format that we'll use for each tournament.  I will look at that this morning and send it in an email if that works>

**Comment by rdwallis** [comment]
You can attach files to issues.  Just drag the file onto the comment field

**Comment by Steve-IZP** [comment]
[Test Schdl_BenchMatric.xlsx](https://github.com/SportsConcierge/scheduler/files/1119644/Test.Schdl_BenchMatric.xlsx)
 I think this should be a standard schedule set up

**Comment by rdwallis** [comment]
This has been updated to handle errors a bit better.

The reason the Test excel fails is because the teams are numbers.  Teams can't be numbers.  It should work if you give the teams names.

**Comment by Steve-IZP** [comment]
Still having an issue, could be me.  But now it's asking me to add Facility: Ice Zone.  But we have it.

**Comment by rdwallis** [comment]
The rink is called ICEZONE which is different to Ice Zone.  You can add an
alias 'Ice Zone' to the rink or rename the rink to Ice Zone and the app
will detect it.

**Comment by Steve-IZP** [comment]
[Test Schdl_BenchMatric.xlsx](https://github.com/SportsConcierge/scheduler/files/1120055/Test.Schdl_BenchMatric.xlsx)
Still not sure what I'm doing wrong.  Thanks for your patience and helping me understand.

**Comment by Steve-IZP** [comment]
Thank you I figured out the issue.  Can we please make the import of the arena name case insensitive?

**Comment by rdwallis** [comment]
The names are now case insensitive
