### ISSUE TITLE
Move Upload Excel Schedule button

### ISSUE THREAD

**Issue by michaeljzucker** [SportsConcierge/scheduler#2]
This should not live in the Divisions area, it should be part of the main tournament screen.

**Comment by rdwallis** [comment]
You can now click on a tournament's name to go to a Tournament screen.

And then upload a schedule from the tournament screen.

The tournament screen is very sparse but eventually it can be the main screen to view a tournament from:

<img width="1093" alt="screen shot 2017-07-03 at 2 48 28 pm" src="https://user-images.githubusercontent.com/534044/27793619-182a909e-5fff-11e7-8f22-23fcf39c4181.png">
